language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.9a1

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.6.11
    - python: "3.2"
      env: DJANGO_VERSION=1.9a
    - python: "3.3"
      env: DJANGO_VERSION=1.6.11
    - python: "3.3"
      env: DJANGO_VERSION=1.9a
    - python: "3.4"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.7.10
    - python: "3.5"
      env: DJANGO_VERSION=1.8.4

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install django==$DJANGO_VERSION
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py develop
  - coverage run --rcfile='django_pluggableappsettings/tests/coverage.conf' --source='./django_pluggableappsettings/' django_pluggableappsettings/tests/travis_ci.py
after_success:
  - coveralls