language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  - DJANGO_VERSION=1.8.19
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.28
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.10
  - DJANGO_VERSION=3.0.3

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0.13
    - python: "2.7"
      env: DJANGO_VERSION=2.1.15
    - python: "2.7"
      env: DJANGO_VERSION=2.2.10
    - python: "2.7"
      env: DJANGO_VERSION=3.0.3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install django==$DJANGO_VERSION
  - pip install coveralls six
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py develop
  - coverage run --rcfile='django_pluggableappsettings/tests/coverage.conf' --source='./django_pluggableappsettings/' django_pluggableappsettings/tests/travis_ci.py
after_success:
  - coveralls