language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "export DISPLAY=:99.0"
services:
  - xvfb
env:
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.10
  - DJANGO_VERSION=3.0.3

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.6.11
    - python: "3.4"
      env: DJANGO_VERSION=2.1.15
    - python: "3.4"
      env: DJANGO_VERSION=2.2.10
    - python: "3.4"
      env: DJANGO_VERSION=3.0.3
    - python: "3.5"
      env: DJANGO_VERSION=3.0.3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install django==$DJANGO_VERSION
  - pip install coveralls six
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py develop
  - coverage run --rcfile='django_pluggableappsettings/tests/coverage.conf' --source='./django_pluggableappsettings/' django_pluggableappsettings/tests/travis_ci.py
after_success:
  - coveralls