language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.10
  - DJANGO_VERSION=2.0.2

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "3.4"
      env: DJANGO_VERSION=1.6.11
    - python: "3.5"
      env: DJANGO_VERSION=1.6.11 #HTMLParseError is no longer supported
    - python: "3.5"
      env: DJANGO_VERSION=1.7.11 #HTMLParseError is no longer supported
    - python: "3.6"
      env: DJANGO_VERSION=1.6.11  #HTMLParseError is no longer supported
    - python: "3.6"
      env: DJANGO_VERSION=1.7.11  #HTMLParseError is no longer supported

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install django==$DJANGO_VERSION
  - pip install coveralls six
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py develop
  - coverage run --rcfile='django_pluggableappsettings/tests/coverage.conf' --source='./django_pluggableappsettings/' django_pluggableappsettings/tests/travis_ci.py
after_success:
  - coveralls